#  Check results of each stage

In [56]:
import pickle
import pandas as pd
import json
import numpy as np

## Parse stage

In [2]:
df = pd.read_csv('./eat_pim/data/RAW_recipes.csv')

In [48]:
df.head()

name      id  minutes  \
0  arriba   baked winter squash mexican style  137739       55   
1            a bit different  breakfast pizza   31490       30   
2                   all in the kitchen  chili  112140      130   
3                          alouette  potatoes   59389       45   
4          amish  tomato ketchup  for canning   44061      190   

   contributor_id   submitted  \
0           47892  2005-09-16   
1           26278  2002-06-17   
2          196586  2005-02-25   
3           68585  2003-04-14   
4           41706  2002-10-25   

                                                tags  \
0  ['60-minutes-or-less', 'time-to-make', 'course...   
1  ['30-minutes-or-less', 'time-to-make', 'course...   
2  ['time-to-make', 'course', 'preparation', 'mai...   
3  ['60-minutes-or-less', 'time-to-make', 'course...   
4  ['weeknight', 'time-to-make', 'course', 'main-...   

                                    nutrition  n_steps  \
0       [51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]       11   
1   [173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]        9   
2  [269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]        6   
3   [368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]       11   
4   [352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]        5   

                                               steps  \
0  ['make a choice and proceed with recipe', 'dep...   
1  ['preheat oven to 425 degrees f', 'press dough...   
2  ['brown ground beef in large pot', 'add choppe...   
3  ['place potatoes in a large pot of lightly sal...   
4  ['mix all ingredients& boil for 2 1 / 2 hours ...   

                                         description  \
0  autumn is my favorite time of year to cook! th...   
1  this recipe calls for the crust to be prebaked...   
2  this modified version of 'mom's' chili was a h...   
3  this is a super easy, great tasting, make ahea...   
4  my dh's amish mother raised him on this recipe...   

                                         ingredients  n_ingredients  
0  ['winter squash', 'mexican seasoning', 'mixed ...              7  
1  ['prepared pizza crust', 'sausage patty', 'egg...              6  
2  ['ground beef', 'yellow onions', 'diced tomato...             13  
3  ['spreadable cheese with garlic and herbs', 'n...             11  
4  ['tomato juice', 'apple cider vinegar', 'sugar...              8

In [22]:
df[df.id == 383560].squeeze().steps

"['cream the margarine with the sugars', 'add the eggs and salt and mix until smooth', 'blend in the baking soda / water mixture', 'add oatmeal , flour , rice krispies , and chocolate chips', 'drop by spoonfuls on a lightly greased cookie sheet', 'bake 10-15 minutes in a 350 oven until lightly browned']"

In [11]:
with open('eat_pim/data/result/parsed_recipes.pkl', 'rb') as file:
    data = pickle.load(file)

In [23]:
data[383560]

{'recipe_name': 'jean s cookies',
 'tags': ['60-minutes-or-less',
  'time-to-make',
  'course',
  'preparation',
  'for-large-groups',
  'drop-cookies',
  'desserts',
  'cookies-and-brownies',
  'number-of-servings'],
 'parsed_steps': {0: {'subj_pred': set(),
   'pred_obj': {('cream', 'margarine', 0, 'dobj')},
   'modifying_subj_pred': set(),
   'modifying_pred_obj': set(),
   'verbs': {'cream'},
   'root_verb': 'cream',
   'noun_chunks': {'margarine', 'sugar'},
   'action_prep_obj': {('cream', 'with', 'sugar', 0)},
   'step_string': 'cream the margarine with the sugars.'},
  1: {'subj_pred': set(),
   'pred_obj': {('add', 'egg', 0, 'dobj'),
    ('add', 'salt', 0, 'conj'),
    ('mix', 'egg', 6, 'dobj'),
    ('mix', 'salt', 6, 'conj')},
   'modifying_subj_pred': set(),
   'modifying_pred_obj': set(),
   'verbs': {'add', 'mix'},
   'root_verb': 'add',
   'noun_chunks': {'egg', 'salt'},
   'action_prep_obj': {('mix', 'until', 'smooth', 6)},
   'step_string': 'add the eggs and salt and mix

## Match phase

In [24]:
with open('eat_pim/data/result/ingredient_list.json', 'r') as json_file:
    data1 = json.load(json_file)

In [25]:
data1[:10]

['pink peppercorn',
 'cream wheat',
 'gruyere',
 'hot pepper sauce',
 'soft fresh goat cheese',
 'white wine',
 'chocolate chip',
 'sweet pickle relish',
 'fresh asparagus',
 'dill']

In [26]:
with open('eat_pim/data/result/word_cleanup_linking.json', 'r') as json_file:
    data2 = json.load(json_file)

In [27]:
list(data2.keys())

['obj_to_ing',
 'obj_to_subobj',
 'obj_leftovers',
 'ing_to_ing',
 'ing_to_foodon',
 'obj_to_foodon',
 'obj_to_equipment',
 'verb_to_preparations']

In [28]:
for key, value in data2.items():
    print(key)
    print()
    for key2, value2 in list(value.items())[:5]:
        print(f'{key2}: {value2}')
    print('-'*50)
    print('\n')

obj_to_ing

cup: []
flan ring: []
dash: []
flavoring packet: []
breadcrumb mix: []
--------------------------------------------------


obj_to_subobj

cup: []
flan ring: ['ring']
dash: []
flavoring packet: ['packet']
breadcrumb mix: ['mix', 'breadcrumb']
--------------------------------------------------


obj_leftovers

cup: cup
flan ring: flan
dash: dash
flavoring packet: flavoring
breadcrumb mix: 
--------------------------------------------------


ing_to_ing

pink peppercorn: ['peppercorn']
cream wheat: []
gruyere: []
hot pepper sauce: ['pepper sauce']
soft fresh goat cheese: ['goat cheese']
--------------------------------------------------


ing_to_foodon

pink peppercorn: ['http://purl.obolibrary.org/obo/FOODON_00003810']
cream wheat: ['http://purl.obolibrary.org/obo/FOODON_00001141']
gruyere: ['http://purl.obolibrary.org/obo/FOODON_03303686']
hot pepper sauce: ['http://purl.obolibrary.org/obo/FOODON_00001956']
soft fresh goat cheese: ['http://purl.obolibrary.org/obo/FOODON_000

## Converting stage

In [50]:
with open('eat_pim/data/result/entity_relations.json', 'r') as json_file:
    data1 = json.load(json_file)

In [51]:
list(data1.keys())[:5]

['subclass_edges', 'subclass_edge_labels']

In [52]:
data1['subclass_edges'][:5]

[['ingredient', 'http://purl.obolibrary.org/obo/FOODON_00001002'],
 ['pink peppercorn', 'peppercorn'],
 ['pink peppercorn', 'http://purl.obolibrary.org/obo/FOODON_00003810'],
 ['cream wheat', 'http://purl.obolibrary.org/obo/FOODON_00001141'],
 ['gruyere', 'http://purl.obolibrary.org/obo/FOODON_03303686']]

In [46]:
data1['subclass_edge_labels'][:5]

['sub', 'sub', 'sub', 'sub', 'sub']

In [48]:
with open('eat_pim/data/result/recipe_tree_data.json', 'r') as json_file:
    data2 = json.load(json_file)

In [49]:
data2['383560']

{'edges': [['pred_cream_383560_0', 'pred_mix_383560_1'],
  ['pred_mix_383560_1', 'pred_blend_383560_2'],
  ['pred_add_383560_1', 'pred_mix_383560_1'],
  ['pred_blend_383560_2', 'pred_add_383560_3'],
  ['pred_add_383560_3', 'pred_drop_383560_4'],
  ['pred_drop_383560_4', 'pred_bake_383560_5'],
  ['pred_bake_383560_5', 'RECIPE_OUTPUT_383560'],
  ['powdered sugar', 'pred_cream_383560_0'],
  ['margarine', 'pred_cream_383560_0'],
  ['granulated sugar', 'pred_cream_383560_0'],
  ['brown sugar', 'pred_cream_383560_0'],
  ['egg', 'pred_add_383560_1'],
  ['salt', 'pred_add_383560_1'],
  ['warm water', 'pred_blend_383560_2'],
  ['rice krispie', 'pred_add_383560_3'],
  ['oatmeal', 'pred_add_383560_3'],
  ['chocolate chip', 'pred_add_383560_3'],
  ['flour', 'pred_add_383560_3']],
 'edge_labels': ['pred mix',
  'pred blend',
  'pred mix',
  'pred add',
  'pred drop',
  'pred bake',
  'RECIPE OUTPUT',
  'pred cream',
  'pred cream',
  'pred cream',
  'pred cream',
  'pred add',
  'pred add',
  'pred

## Additional transformations stage

In [ ]:
# seems not interesting 

## Training stage

In [111]:
data1 = np.load('eat_pim/data/result/models/result_model/entity_embedding.npy')

In [115]:
data1.shape

(14544, 200)

In [113]:
data1

array([[-0.15730566, -0.16300571,  0.17372206, ..., -0.11723914,
        -0.03799069,  0.1553396 ],
       [ 0.1048282 ,  0.00267288, -0.11163474, ...,  0.0121008 ,
        -0.07867005,  0.00126089],
       [ 0.19304666,  0.18816614,  0.19701171, ...,  0.04317206,
         0.06295916, -0.02250869],
       ...,
       [ 0.08771458,  0.16975832,  0.05831364, ..., -0.16495588,
        -0.13149978, -0.00118239],
       [-0.13572384, -0.04644216,  0.02138443, ...,  0.03580434,
         0.20595698,  0.09834994],
       [-0.10202004,  0.15860766,  0.07565844, ...,  0.03308149,
         0.04762605,  0.09335016]], dtype=float32)

In [112]:
data2= np.load('eat_pim/data/result/models/result_model/relation_embedding.npy')

In [116]:
data2.shape

(337, 200)

In [114]:
data2

array([[-0.04506266,  0.07760882, -0.10665913, ...,  0.12019925,
        -0.09497406,  0.04320364],
       [ 0.04970494, -0.05062789,  0.12367373, ..., -0.00666023,
        -0.02488038, -0.06820279],
       [-0.12450725,  0.07386997, -0.03578743, ...,  0.09905669,
         0.14897479, -0.0793221 ],
       ...,
       [ 0.01686067, -0.00877547, -0.07808621, ...,  0.04358712,
        -0.05034246,  0.12145896],
       [-0.02194676,  0.02441711, -0.05962902, ..., -0.02604868,
        -0.0987896 , -0.04782353],
       [ 0.08043953,  0.02161094, -0.06800458, ..., -0.05121616,
         0.08861237, -0.07131154]], dtype=float32)

In [117]:
# entities and actions themselves are in 'eat_pim/data/result/eatpim_triple_data/' in 'entities.dict' and 'relations.dict'

## Co-occurence matrix

In [57]:
with open('eat_pim/data/result/ing_occ_data.pkl', 'rb') as file:
    data = pickle.load(file)

In [78]:
len(data['ing_to_index'])

676

In [64]:
matrix = data['ing_cooc_matrix'].toarray()

In [65]:
matrix.shape

(676, 676)

In [75]:
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [76]:
np.max(matrix)

24.0

In [80]:
with open('eat_pim/data/result/word_cleanup_linking.json', 'r') as json_file:
    data2 = json.load(json_file)

In [84]:
len(data2['ing_to_foodon'])

846

In [89]:
l = []
for ing in data['ing_to_index']:
    l.append(ing in data2['ing_to_foodon'])
    
sum(l)

647