#  Check results of each stage

In [1]:
import pickle
import pandas as pd
import json
import numpy as np

## Parse stage

In [2]:
df = pd.read_csv('./eat_pim/data/RAW_recipes.csv')

In [3]:
df.head()

name      id  minutes  \
0  arriba   baked winter squash mexican style  137739       55   
1            a bit different  breakfast pizza   31490       30   
2                   all in the kitchen  chili  112140      130   
3                          alouette  potatoes   59389       45   
4          amish  tomato ketchup  for canning   44061      190   

   contributor_id   submitted  \
0           47892  2005-09-16   
1           26278  2002-06-17   
2          196586  2005-02-25   
3           68585  2003-04-14   
4           41706  2002-10-25   

                                                tags  \
0  ['60-minutes-or-less', 'time-to-make', 'course...   
1  ['30-minutes-or-less', 'time-to-make', 'course...   
2  ['time-to-make', 'course', 'preparation', 'mai...   
3  ['60-minutes-or-less', 'time-to-make', 'course...   
4  ['weeknight', 'time-to-make', 'course', 'main-...   

                                    nutrition  n_steps  \
0       [51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]       11   
1   [173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]        9   
2  [269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]        6   
3   [368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]       11   
4   [352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]        5   

                                               steps  \
0  ['make a choice and proceed with recipe', 'dep...   
1  ['preheat oven to 425 degrees f', 'press dough...   
2  ['brown ground beef in large pot', 'add choppe...   
3  ['place potatoes in a large pot of lightly sal...   
4  ['mix all ingredients& boil for 2 1 / 2 hours ...   

                                         description  \
0  autumn is my favorite time of year to cook! th...   
1  this recipe calls for the crust to be prebaked...   
2  this modified version of 'mom's' chili was a h...   
3  this is a super easy, great tasting, make ahea...   
4  my dh's amish mother raised him on this recipe...   

                                         ingredients  n_ingredients  
0  ['winter squash', 'mexican seasoning', 'mixed ...              7  
1  ['prepared pizza crust', 'sausage patty', 'egg...              6  
2  ['ground beef', 'yellow onions', 'diced tomato...             13  
3  ['spreadable cheese with garlic and herbs', 'n...             11  
4  ['tomato juice', 'apple cider vinegar', 'sugar...              8

In [4]:
df[df.id == 323553].squeeze().steps

"['in a large pot , brown the deer and pork', 'spoon off excess grease , but do not drain completely', 'add onions and cook until tender', 'add 3 cups water , tomato sauce , diced tomatoes , garlic , italian seasoning , bay leaves , soy sause , salt , black pepper , garlic powder and seasoned salt', 'cook covered for 20-25 minutes', 'add the elbow macaroni , cover and continue to simmer for about 20 minutes', 'turn off the heat , remove the bay leaves and let sit about 30 minutes']"

In [10]:
df[df.id == 323553].squeeze().ingredients

"['ground deer meat', 'ground pork', 'onions', 'water', 'tomato sauce', 'diced tomatoes', 'garlic cloves', 'soy sauce', 'bay leaves', 'italian seasoning', 'salt', 'black pepper', 'garlic powder', 'seasoning salt', 'elbow macaroni']"

In [13]:
with open('eat_pim/data/result/parsed_recipes.pkl', 'rb') as file:
    data = pickle.load(file)

In [14]:
data[323553]

{'recipe_name': 'shane s goulash',
 'tags': ['time-to-make',
  'course',
  'preparation',
  'main-dish',
  'one-dish-meal',
  '4-hours-or-less'],
 'parsed_steps': {0: {'subj_pred': set(),
   'pred_obj': {('brown', 'deer', 5, 'dobj'), ('brown', 'pork', 5, 'conj')},
   'modifying_subj_pred': set(),
   'modifying_pred_obj': set(),
   'verbs': {'brown'},
   'root_verb': 'brown',
   'noun_chunks': {'deer', 'large pot', 'pork'},
   'action_prep_obj': {('brown', 'in', 'large pot', 5)},
   'step_string': 'in a large pot, brown the deer and pork.'},
  1: {'subj_pred': set(),
   'pred_obj': {('drain', 'excess grease', 8, 'dobj'),
    ('spoon off', 'excess grease', 0, 'dobj')},
   'modifying_subj_pred': set(),
   'modifying_pred_obj': set(),
   'verbs': {'drain', 'spoon off'},
   'root_verb': 'spoon off',
   'noun_chunks': {'excess grease'},
   'action_prep_obj': set(),
   'step_string': 'spoon off excess grease, but do not drain completely.'},
  2: {'subj_pred': set(),
   'pred_obj': {('add', 'o

## Match phase

In [15]:
with open('eat_pim/data/result/ingredient_list.json', 'r') as json_file:
    data1 = json.load(json_file)

In [16]:
data1[:10]

['white wheat flour',
 'peaches juice',
 'lavender flower',
 'carob chip',
 'almond flavored liqueur',
 'crunchy peanut butter',
 'raw chicken',
 'peri peri',
 'instant espresso',
 'vegetarian chicken flavored broth mix']

In [17]:
with open('eat_pim/data/result/word_cleanup_linking.json', 'r') as json_file:
    data2 = json.load(json_file)

In [18]:
list(data2.keys())

['obj_to_ing',
 'obj_to_subobj',
 'obj_leftovers',
 'ing_to_ing',
 'ing_to_foodon',
 'obj_to_foodon',
 'obj_to_equipment',
 'verb_to_preparations']

In [19]:
for key, value in data2.items():
    print(key)
    print()
    for key2, value2 in list(value.items())[:5]:
        print(f'{key2}: {value2}')
    print('-'*50)
    print('\n')

obj_to_ing

packaged cheese sauce: ['cheese sauce']
flat dough scraper: []
guava gel: []
cooker cover: []
1 / 2 cup olive oil: ['olive oil']
--------------------------------------------------


obj_to_subobj

packaged cheese sauce: []
flat dough scraper: ['dough scraper', 'flat']
guava gel: []
cooker cover: ['cover', 'cooker']
1 / 2 cup olive oil: ['cup']
--------------------------------------------------


obj_leftovers

packaged cheese sauce: packaged
flat dough scraper: 
guava gel: guava gel
cooker cover: 
1 / 2 cup olive oil: 
--------------------------------------------------


ing_to_ing

white wheat flour: ['wheat flour']
peaches juice: ['juice']
lavender flower: []
carob chip: ['chip']
almond flavored liqueur: ['liqueur']
--------------------------------------------------


ing_to_foodon

white wheat flour: ['http://purl.obolibrary.org/obo/FOODON_00001210']
lavender flower: ['http://purl.obolibrary.org/obo/FOODON_00002571']
carob chip: ['http://purl.obolibrary.org/obo/FOODON_00

## Converting stage

In [20]:
with open('eat_pim/data/result/entity_relations.json', 'r') as json_file:
    data1 = json.load(json_file)

In [21]:
list(data1.keys())[:5]

['subclass_edges', 'subclass_edge_labels']

In [22]:
data1['subclass_edges'][:5]

[['ingredient', 'http://purl.obolibrary.org/obo/FOODON_00001002'],
 ['white wheat flour', 'wheat flour'],
 ['white wheat flour', 'http://purl.obolibrary.org/obo/FOODON_00001210'],
 ['peaches juice', 'juice'],
 ['lavender flower', 'http://purl.obolibrary.org/obo/FOODON_00002571']]

In [23]:
data1['subclass_edge_labels'][:5]

['sub', 'sub', 'sub', 'sub', 'sub']

In [8]:
with open('eat_pim/data/result/recipe_tree_data.json', 'r') as json_file:
    data2 = json.load(json_file)

In [11]:
data2['323553']

{'edges': [['pred_brown_323553_0', 'pred_drain_323553_1'],
  ['pred_drain_323553_1', 'pred_cook_323553_2'],
  ['pred_cook_323553_2', 'pred_add_323553_3'],
  ['pred_add_323553_2', 'pred_cook_323553_2'],
  ['pred_add_323553_3', 'pred_cook_323553_4'],
  ['pred_cook_323553_4', 'pred_turn off_323553_6'],
  ['pred_simmer_323553_5', 'pred_sit_323553_6'],
  ['pred_add_323553_5', 'pred_cover_323553_5'],
  ['pred_cover_323553_5', 'pred_continue_323553_5'],
  ['pred_continue_323553_5', 'pred_simmer_323553_5'],
  ['pred_turn off_323553_6', 'pred_remove_323553_6'],
  ['pred_remove_323553_6', 'pred_sit_323553_6'],
  ['pred_sit_323553_6', 'RECIPE_OUTPUT_323553'],
  ['soy sauce', 'pred_add_323553_3'],
  ['ground deer meat', 'pred_brown_323553_0'],
  ['ground pork', 'pred_brown_323553_0'],
  ['onion', 'pred_add_323553_2'],
  ['garlic powder', 'pred_add_323553_3'],
  ['seasoning salt', 'pred_add_323553_3'],
  ['salt', 'pred_add_323553_3'],
  ['bay leave', 'pred_add_323553_3'],
  ['water', 'pred_add_3235

## Additional transformations stage

In [26]:
# seems not interesting 

## Training stage

In [27]:
data1 = np.load('eat_pim/data/result/models/result_model/entity_embedding.npy')

In [28]:
data1.shape

(35282, 200)

In [29]:
data1

array([[-0.10066131,  0.14847583, -0.15372162, ...,  0.12440923,
         0.21558975,  0.23338735],
       [ 0.09728201, -0.20305832,  0.18482757, ..., -0.16855279,
        -0.1914247 , -0.13457297],
       [ 0.07848426, -0.12518491, -0.05750352, ..., -0.13136351,
        -0.14900945, -0.18839473],
       ...,
       [-0.00497519,  0.11228769, -0.09535457, ...,  0.13634567,
        -0.08575971,  0.16163759],
       [ 0.40133262,  0.38285762, -0.36362553, ..., -0.07466532,
        -0.3443854 , -0.17436528],
       [ 0.27345806,  0.31066573, -0.0364875 , ..., -0.04268415,
        -0.36825085, -0.22395949]], dtype=float32)

In [30]:
data2= np.load('eat_pim/data/result/models/result_model/relation_embedding.npy')

In [31]:
data2.shape

(2155, 200)

In [32]:
data2

array([[-0.0168477 ,  0.02033207,  0.0268926 , ..., -0.05902204,
        -0.06585746,  0.0525561 ],
       [ 0.1453441 ,  0.02742632,  0.01849286, ...,  0.03945448,
         0.00857689,  0.05027134],
       [-0.04293855, -0.03937368, -0.00558591, ..., -0.01837298,
         0.06250891, -0.01247513],
       ...,
       [ 0.04315095, -0.03737517,  0.10287715, ...,  0.02799555,
         0.09120946,  0.02514532],
       [ 0.09208161,  0.05382334,  0.01891737, ..., -0.05668677,
         0.01494567, -0.01267082],
       [-0.09248153,  0.01737149,  0.02265623, ...,  0.035187  ,
         0.01850378,  0.01055231]], dtype=float32)

In [33]:
# entities and actions themselves are in 'eat_pim/data/result/eatpim_triple_data/' in 'entities.dict' and 'relations.dict'

## Co-occurence matrix

In [2]:
with open('eat_pim/data/result/ing_occ_data.pkl', 'rb') as file:
    data = pickle.load(file)

In [3]:
len(data['ing_to_index'])

5764

In [4]:
matrix = data['ing_cooc_matrix'].toarray()

In [5]:
matrix.shape

(5764, 5764)

In [38]:
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [39]:
np.max(matrix)

1489.0

In [40]:
with open('eat_pim/data/result/word_cleanup_linking.json', 'r') as json_file:
    data2 = json.load(json_file)

In [41]:
len(data2['ing_to_foodon'])

5943

In [42]:
l = []
for ing in data['ing_to_index']:
    l.append(ing in data2['ing_to_foodon'])
    
sum(l)

5219